# Generated by Django 5.0.1 on 2024-02-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Retypepass', models.CharField(max_length=20, null=True)),
                ('phonenumber', models.IntegerField()),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Age', models.IntegerField()),
                ('Bloodgroup', models.CharField(choices=[('o+ive', 'O+ive'), ('b+ive', 'B+ive'), ('a+ive', 'A+ive'), ('o-ive', 'O-ive'), ('a-ive', 'a-ive'), ('b-ive', 'b-ive'), ('ab+ive', 'AB+ive'), ('ab-ive', 'AB-ive'), ('other', 'OTHER')], max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('select', 'select'), ('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
            ],
        ),
    ]
