# Generated by Django 5.0.1 on 2024-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_alter_students_address_alter_students_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Bloodgroup',
        ),
        migrations.RemoveField(
            model_name='students',
            name='image',
        ),
        migrations.AlterField(
            model_name='students',
            name='Age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phonenumber',
            field=models.IntegerField(blank=True),
        ),
    ]
