# Generated by Django 5.0.1 on 2024-02-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_remove_students_bloodgroup_remove_students_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='jaga',
        ),
    ]
