# Generated by Django 5.0.1 on 2024-02-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0009_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
    ]
