# Generated by Django 5.0.1 on 2024-02-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0010_alter_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Bloodgroup',
            field=models.CharField(blank=True, choices=[('o+ive', 'O+ive'), ('b+ive', 'B+ive'), ('a+ive', 'A+ive'), ('o-ive', 'O-ive'), ('a-ive', 'a-ive'), ('b-ive', 'b-ive'), ('ab+ive', 'AB+ive'), ('ab-ive', 'AB-ive'), ('other', 'OTHER')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
