# Generated by Django 5.0.1 on 2024-02-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0012_remove_students_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Bloodgroup',
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
