# Generated by Django 5.0.1 on 2024-02-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0014_remove_students_gender_remove_students_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
    ]
