# Generated by Django 5.0.1 on 2024-02-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0015_rename_phonenumber_students_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Phonenumber',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Retypepass',
        ),
    ]
