# Generated by Django 5.0.1 on 2024-02-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0017_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
