# Generated by Django 5.0.1 on 2024-02-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0018_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Retypepass',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
