# Generated by Django 5.0.1 on 2024-02-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0019_students_phonenumber_students_retypepass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Phonenumber',
        ),
    ]
