# Generated by Django 5.0.1 on 2024-03-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0022_students_address_students_age_students_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.BooleanField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
    ]
